### ISSUE TITLE
/project/kumoh page not found error

### ISSUE THREAD

**Issue by JayJayDee** [JayJayDee/minecraft-info-webpage#7]
금오공대 소개 페이지 `/project/kumoh` 가 존재하지 않아 에러가 발생하고 있는데 
이거 작업을 부탁드림다 

`/src/express-app/page-endpoints` 에 추가하시고 렌더할 ejs 파일만들어서 뚝딱 만드세여

**Comment by lskmagic** [comment]
일단 추가해두었습니다.
부지 정리좀 되고 큰윤곽이 나오면 제대로 업데이트 하도록 하겠습니다.

**Comment by JayJayDee** [comment]
@lskmagic 지렸읍니다 👍
